name: "Kiểm tra mã HTML"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
    # Path of the files to test
          root: ./
    # Format for logging output. Valid values: gnu, xml, json, text
          format: xml
    # Logging Level. Valid values: DEBUG, INFO, WARNING. Default: WARNING
          log_level: WARNING
    # Checks css as well
          css: true
      - uses: actions/upload-artifact@v3
        with:
          name: log
          path: log.log
