name: Cập nhật tệp .md sang tệp .html

on:
  push:
    branches: [ main ]
    paths:
      - 'md2html.py'
      - 'mdtohtml.py'
      - 'tournament-winner/list-winner/*.md'
      - 'tournament-winner/top/*.md'

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
      - name: Thiết lập Python '3.11'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Cài đặt dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Cập nhật Bảng xếp hạng
        run: |
          python3 md2html.py
          python3 mdtohtml.py
      - name: Cam kết & Đẩy tệp
        run: |
          git config --local user.email "vietdinh856@gmail.com"
          git config --local user.name "TVLT-Admim"
          git add -A
          git commit -m "Cập nhật bảng xếp hạng lên web"
          git push --force
