name: Tự động cập nhật các kho lưu trữ

on:
  schedule:
    - cron: "14 */03 */20 */09 *"
  workflow_dispatch:

jobs:
  updating:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cập nhật cam kết
        run: |
          git submodule update --remote
          git config --local user.email "142654223+TVLT-Admin@users.noreply.github.com"
          git config --local user.name "TVLT-Admin"
          git add -A
          git commit -m " "
          git push --force
