name: Tự động cập nhật các kho lưu trữ

on:
  schedule:
    - cron: "14 */03 */20 */09 *"
  workflow_dispatch:

jobs:
  updating:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cập nhật cam kết
        run: |
          git config --global user.email "vietdinh856@gmail.com"
          git config --global user.name "TVLT-Admin"
          git config --global pull.rebase false --allow-unrelated-histories
          git submodule init 
          git submodule update --remote --recursive
          git submodule update
          git submodule update --remote
          git commit -a
          git commit -m " "
          git push
