name: Cập nhật các repository liên quan

on:
  schedule:
    - cron: "14 */03 */20 */09 *"
  workflow_dispatch:

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  updating:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
      - name: Cập nhật cam kết
        run: |
          git config --global user.email "vietdinh856@gmail.com"
          git config --global user.name "TVLT-Admin"
          git config --global pull.rebase false --allow-unrelated-histories
          git submodule init 
          git submodule update --remote --recursive
          git submodule update
          git add .
          git commit -m "Cập nhật các repository"
          git push origin HEAD:main
