name: Test chính tả HTML

on: [push, pull_request]

jobs:
  conformance:
    name: Check document-conformance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: marcuslindblom/w3cvalidator
      - uses: marcuslindblom/w3cvalidator@main
        with:
          url: ${{ secrets.URL }}
          level: error
