name: Kiểm tra chính tả HTML

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Check Spelling
      uses: check-spelling/check-spelling@v0.0.22
