name: Submodule Updates

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]


jobs:
  build:
    name: Submodule update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: run action
        run: |
          git submodule add https://github.com/Thi-Vua-Lay-Tot/libot-leaderboard
